services:
  test-backend-dotnet:
    build:
      target: development
    image: test-backend-dotnet-development
    container_name: test-backend-dotnet-test
    user: root
    entrypoint: sh -c "cd /home/dotnet && chown -R dotnet:dotnet . && su dotnet -c 'dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=./test-output/'"
    volumes:
      - ./Test.Backend.Dotnet.sln:/home/dotnet/Test.Backend.Dotnet.sln
      - ./src/Test.Backend.Dotnet.Core:/home/dotnet/src/Test.Backend.Dotnet.Core
      - ./test/Test.Backend.Dotnet.Core.Tests:/home/dotnet/test/Test.Backend.Dotnet.Core.Tests
      - ./src/Test.Backend.Dotnet.Api:/home/dotnet/src/Test.Backend.Dotnet.Api
      - ./test/Test.Backend.Dotnet.Api.Tests:/home/dotnet/test/Test.Backend.Dotnet.Api.Tests
      - ./test/Test.Backend.Dotnet.Api.Tests/test-output:/home/dotnet/test/Test.Backend.Dotnet.Api.Tests/test-output
      - ./test/Test.Backend.Dotnet.Core.Tests/test-output:/home/dotnet/test/Test.Backend.Dotnet.Core.Tests/test-output
